# Generated by Django 5.0.2 on 2025-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('applicant', 'Applicant'), ('employee', 'Employee')], max_length=10),
        ),
    ]
