# Generated by Django 5.0.2 on 2025-07-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employee', 'Employee')], max_length=10),
        ),
    ]
